language: node_js

node_js:
  - "12"

cache:
  directories:
    - "node_modules"

install: true

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      deploy:
        provider: heroku
        api_key: "$HEROKU_API_KEY"
        app: "test-multiplayer-game"
        skip_cleanup: true
